[alembic]
# path to migration scripts
script_location = alembic

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = consoleHandler

[formatters]
keys = genericFormatter

[logger_root]
level = WARN
handlers = consoleHandler

[logger_sqlalchemy]
level = INFO
handlers = consoleHandler
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = consoleHandler
qualname = alembic

[handler_consoleHandler]
class = StreamHandler
args = []
level = DEBUG
formatter = genericFormatter

[formatter_genericFormatter]
format = %(asctime)s [%(levelname)s]: %(message)s

